### PR TITLE
Damage

### PR DESCRIPTION
**Pull request by sweeneyde**
After this you should be able to to push E to get knocked back and be dealt damage

### CODE REVIEW

**Comment by bhasseman** [comment]
I got an error from line 49 of LinkTextureStorage.cs - the link_damaged_black/blue/red files aren't added to the Content.mgcb file which caused it to fail loading the texture and wouldn't compile. Is this an error on my end, or is anyone else getting this? It's a simple fix just have to add them into the Content pipeline

**Comment by bhasseman** [comment]
> I got an error from line 49 of LinkTextureStorage.cs - the link_damaged_black/blue/red files aren't added to the Content.mgcb file which caused it to fail loading the texture and wouldn't compile. Is this an error on my end, or is anyone else getting this? It's a simple fix just have to add them into the Content pipeline

I added the files into Content manually on my end and it compiled and ran fine - pressing E and moving in each direction works as expected. However you have the initial state of Player set to be the KnockbackSouth state, so when the game is first started it damages Link and knocks him downward. Not sure if you did that for testing purposes and left it in by mistake, but that was the only other thing I noticed. Everything else looks good on my end, good work

**Comment by sweeneyde** [comment]
Hopefully those commits fix it -- let me know if they don't.

**Comment by royjpark** [comment]
Just pulled and everything looks good to me. Files are included now and Link doesn't start in a knocked back state. Nice work!

**Review by bhasseman — APPROVED** [review]
After the last few commits, everything builds and runs as expected. LGTM, good work

**Pull request merged**
