### PR TITLE
Gamepad Implementation

### PR DESCRIPTION
**Pull request by wchiraz**

### CODE REVIEW

**Review by wchiraz — COMMENTED** [review]
In gamepadcontroller.cs, can delete capabilities line in update method.

**Review by bhasseman — COMMENTED** [review]
Works with the 360 controller I used, code looks good. One thing that's missing is opening the inventory, could maybe bind that to one of the triggers as all the other buttons are being used for something else.

**Comment by rustbeltdurt** [comment]
Same comments as Brent. All in game stuff seems to work well. Inventory opening and menu interaction are not working but should be added.

**Comment by jfc978** [comment]
Works on my 360 controller. Inventory and previous bugs seem to be fixed. Hardcoded controls are not preferred in the GameState, but that can be fixed later

**Pull request merged**
