### PR TITLE
Chests

### PR DESCRIPTION
**Pull request by rustbeltdurt**
I will merge w/ main after this is checked out. Only example of the chest is in the first room, I will add them in their final positions once this in main. To trigger the chest, walk to the front of it.

### CODE REVIEW

**Review by bhasseman — COMMENTED** [review]
Chest hitbox works on all 4 sides (pushes back on left/top/right, opens on bottom), Link shows the item that he got from the chest after opening it, bottom side pushes back when the chest is open - all looks really good.
Only weird thing is that the item Link shows after opening the chest (the dungeon map in the first room, for example) display a bit strangely, seems like the source rectangle is off or something (I haven't looked into it yet). Other than that, LGTM

**Comment by royjpark** [comment]
Same comments as Brent essentially, pushback works on all sides and opens on bottom side. Is the chest supposed to unlock with a sword strike? Because the chest seems to open for me without a sword strike. Also agree on item looking a little weird when Link holds it. Other than that LGTM.

**Review by bhasseman — COMMENTED** [review]
Most recent commits have fixed any issues found by me, once the conflicts with the CSVs are fixed it should be good to merge.

**Comment by jfc978** [comment]
Chests and animation look good. Ready to merge

**Pull request merged**
