### PR TITLE
Update with Rest and Quit

### PR DESCRIPTION
**Pull request by jfc978**
Added reset and quit commands to keyboard

### CODE REVIEW

**Comment by sweeneyde** [comment]
I'm getting

```
KeyMapping.cs(53,41,53,50): error CS0246: The type or namespace name 'ResetGame' could not be found (are you missing a using directive or an assembly reference?)
```

**Comment by sweeneyde** [comment]
I think you need to include the .csproj in the commit and it should be fine though

**Comment by rustbeltdurt** [comment]
Compiled and ran perfectly fine after the missing file fix. No recommendations on code quality because this is temporary functionality for the sprint.

LGTM

**Comment by bhasseman** [comment]
Quit and Reset command work as expected, along with all other previously implemented commands. However, I accidentally fat-fingered the D4 key and the program crashed - if any keys that were not added to the keyCommands list and they are pressed, a crash occurs. Not sure how urgent it is for this sprint, but something that may be worth looking into.

**Comment by rustbeltdurt** [comment]
> Quit and Reset command work as expected, along with all other previously implemented commands. However, I accidentally fat-fingered the D4 key and the program crashed - if any keys that were not added to the keyCommands list and they are pressed, a crash occurs. Not sure how urgent it is for this sprint, but something that may be worth looking into.

Good catch. We should defo check that out.

**Comment by jfc978** [comment]
The non-mapped key issue should be fixed. It's something I accidentally removed when adding the two new commands

**Comment by rustbeltdurt** [comment]
Pulled and ran after non-mapped key fix. LGTM

**Pull request merged**
