### PR TITLE
Sword Key Binds

### PR DESCRIPTION
**Pull request by royjpark**
Just changed attack from space to 'n' and 'z'.

### CODE REVIEW

**Comment by royjpark** [comment]
Also, do we need `updateKeyCommand` on line 98? It's been commented out.

**Comment by sweeneyde** [comment]
I think the commented-out `updateKeyCommand` can be deleted. Other than that, LGTM

**Comment by jfc978** [comment]
Looks good, hopefully no issues with other command commit

**Comment by bhasseman** [comment]
LGTM

**Pull request merged**
