### PR TITLE
Commands

### PR DESCRIPTION
**Pull request by jfc978**
Adding commands to handle ILink state transitions. ILink has been updated with six additional method bodies for each of the four directions, as well as primary and secondary attacks. These methods are called from the keyboard controller during the update method. 

Currently improving key priority order to improve fluidity of movement

### CODE REVIEW

**Comment by sweeneyde** [comment]
LGTM, visually

**Comment by sweeneyde** [comment]
Project now builds as well

**Comment by sweeneyde** [comment]
We could reduce coupling in the future (if needed) by making commands call only player.Method(), not player.currentState.Method()

**Comment by sweeneyde** [comment]
Still works

**Comment by bhasseman** [comment]
Builds and runs well on my end, looks good visually. Are we including .suo files in commits? If it doesn't matter, should be good to merge.

**Pull request merged**
