### PR TITLE
Added ability to cycle through rooms with LMB/RMB

### PR DESCRIPTION
**Pull request by bhasseman**
Simply "increments" or "decrements" the room ID (i.e. if room ID is "005", it will go to "004" or "006")
Had to make map public in Game1.cs, and currentRoom public in Map.cs
Right now it is implemented directly into the MouseController class, though it may be better if I do something similar to the KeyController class (i.e. make the mappings and have it execute commands instead). Wasn't sure if it was necessary since this is just a temporary implementation that is only used for testing.

### CODE REVIEW

**Comment by sweeneyde** [comment]
This is building and working for me.

**Comment by sweeneyde** [comment]
How do we unite this with the DevRoom stuff? It seems that there's always just one block and one enemy and one item, while the background changes are exclusively visual.

**Comment by jfc978** [comment]
All of the background stuff is the sprite sheet. We will need to code the new blocks and entities into the appropriate csv files for them to load in

**Comment by jfc978** [comment]
Code looks good and can be merged

**Comment by bhasseman** [comment]
The block/enemy/world item are coded into each room csv, Josh is working on fixing that to make it so that we can make the blocks appear correctly given x and y coordinates, so right now each room will have the stairs and key in it.

**Pull request merged**
