### PR TITLE
don't equip items we dont have

### PR DESCRIPTION
**Pull request by sweeneyde**

### CODE REVIEW

**Review by bhasseman — COMMENTED** [review]
Code looks good, builds and works correctly. LGTM

**Comment by rustbeltdurt** [comment]
Bomb present in inventory screen, but it shouldn't be. When changing the "rupeeCount = keyCount = bombCount = 1;" to a value of "0", the bomb is unusable, but graphic is still present within the inventory screen.

**Comment by sweeneyde** [comment]
@joshwhite2893 If you make `bombCount == 0` then you would also have to delete the line above it: 
```cs
            //for now this is added here
            inventory.Add(typeof(Bomb));
```

**Comment by jfc978** [comment]
Most recent update looks good. No additional items in starting inventory

**Pull request merged**
