### PR TITLE
Heart

### PR DESCRIPTION
**Pull request by royjpark**
Heart drops in same location for each room that has enemies

I watched gameplay video again and saw that heart restores 1 full heart, so I've implemented it like that for now. Thoughts?
If giving a full heart for every room is too much, should I lower it back down to 1/2 heart? Or should I implement RNG to determine if heart spawns after room is cleared?
Lastly, should a heart spawn after killing the boss?

EDIT:
ignore the first 15 of the 16 commits since i checked this branch out from npc refactor and it hasn't been merged yet. tbh I'm not sure how to get rid of the irrelevant file changes and commits so im really sorry about that but the files that I changed that are relevant for this PR are:
- csvs for heart placement
- inventory manager for heart action
- worlditemtexturestorage to add a new spritesheet and change heart rectangle
- heart.cs within worlditems to get new spritesheet

### CODE REVIEW

**Comment by jfc978** [comment]
There's a content load error when loading heart_sheet. I switch "heart_sheet" to "HUD_spritesheet" and that seems to work fine, though I'm unsure why it doesnt work for heart_sheet.
Besides having a black background, the heart seems to spawn just fine and only after enemies are killed.

**Comment by royjpark** [comment]
> There's a content load error when loading heart_sheet. I switch "heart_sheet" to "HUD_spritesheet" and that seems to work fine, though I'm unsure why it doesnt work for heart_sheet.
> Besides having a black background, the heart seems to spawn just fine and only after enemies are killed.

Weird.. I made a separate "heart_sheet" that had a transparent background but I wonder if I accidentally removed it along with the other mgcontent stuff. I tried adding it and pushing it again, could you try it again?

**Review by bhasseman — APPROVED** [review]
The heart_sheet file fixed the problem described, and the heart also no longer has a black background. Heart only spawns when all enemies are killed, and can be picked up when walked over. Adds 1 full heart to Link when it is picked up (unless he is at 5 or 6 health, then it adds 1 or 0, respectively). Seems to be working correctly, good work.
LGTM

**Comment by jfc978** [comment]
That seems to fix all of the issues, so I'm going to go ahead and merge everything

**Pull request merged**
